### ISSUE TITLE
mapillary_tools upload exception pymp4 major brand string

### ISSUE THREAD

**Issue by moenk** [mapillary/mapillary_tools#439]
`D:\Mapillary\mapillary_tools>C:\Python38\python.exe -m mapillary_tools process_and_upload  --import_path "D:\Mapillary\DCIM" --user_name "moenk"
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Mapillary\mapillary_tools\mapillary_tools\__main__.py", line 6, in <module>
    from .commands import authenticate
  File "D:\Mapillary\mapillary_tools\mapillary_tools\commands\__init__.py", line 2, in <module>
    from . import process
  File "D:\Mapillary\mapillary_tools\mapillary_tools\commands\process.py", line 4, in <module>
    from ..insert_MAPJson import insert_MAPJson
  File "D:\Mapillary\mapillary_tools\mapillary_tools\insert_MAPJson.py", line 9, in <module>
    from . import image_log, types, processing, error
  File "D:\Mapillary\mapillary_tools\mapillary_tools\processing.py", line 16, in <module>
    from .gpx_from_blackvue import gpx_from_blackvue
  File "D:\Mapillary\mapillary_tools\mapillary_tools\gpx_from_blackvue.py", line 8, in <module>
    from pymp4.parser import Box
  File "C:\Python38\lib\site-packages\pymp4\parser.py", line 86, in <module>
    "major_brand" / String(4),
NameError: name 'String' is not defined`
Note: Not any MP4, only JPG files.

**Comment by ptpt** [comment]
@moenk it seems to be related to the construct library used in pymp4 https://construct.readthedocs.io/en/latest/

A refresh reinstall should solve the issue (recommend virtualenv https://github.com/mapillary/mapillary_tools#development)

I will check if it's possible to lock pip dependency versions so this won't happen again.

**Comment by GITNE** [comment]
It seems like I am having the same problem. I have installed pymp4 1.2.0 and construct 2.10.67 and it just falls apart. I cannot even run a simple `--version` option.

> I will check if it's possible to lock pip dependency versions so this won't happen again.

Or better yet, file a bug with pymp4 to accommodate for any changes in construct.

**Comment by GITNE** [comment]
After a downgrade to pymp4 1.1.0 it still does not work. :disappointed: It’s just abysmal. Now what? Am I supposed to figure out what version of construct worked with pymp4 1.1.0? This is just ridiculous :exploding_head:
